DROP TABLE IF EXISTS alarms;
CREATE TABLE alarms (
	_id INTEGER PRIMARY KEY AUTOINCREMENT,
	description TEXT NOT NULL,
	hour INTEGER NOT NULL,
	minute INTEGER NOT NULL,
	day INTEGER NOT NULL
);
INSERT INTO alarms VALUES(null, "Test", 12, 50, 3)